# Generated by Django 2.2.2 on 2020-09-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0004_auto_20200910_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
    ]
